Building configuration...

Current configuration:
!
frr version 8.2.2
frr defaults traditional
hostname PARI_router
!
ip route 29.0.0.0/8 blackhole
!
interface ext_30_PARI
 ip address 179.29.30.1/30
exit
!
interface host
 ip address 29.103.0.2/24
exit
!
interface lo
 ip address 29.153.0.1/32
exit
!
interface matrix_29
 ip address 29.0.198.1/24
exit
!
interface port_HAML
 ip address 29.0.1.2/30
exit
!
interface port_LOND
 ip address 29.0.4.1/30
exit
!
interface port_NEWY
 ip address 29.0.5.1/30
 ip ospf cost 30
exit
!
interface port_TRGA
 ip address 29.0.3.1/30
exit
!
interface port_ZURI
 ip address 29.0.6.1/30
exit
!
router bgp 29
 bgp router-id 29.153.0.1
 neighbor 29.151.0.1 remote-as 29
 neighbor 29.151.0.1 update-source lo
 neighbor 29.152.0.1 remote-as 29
 neighbor 29.152.0.1 update-source lo
 neighbor 29.154.0.1 remote-as 29
 neighbor 29.154.0.1 update-source lo
 neighbor 29.155.0.1 remote-as 29
 neighbor 29.155.0.1 update-source lo
 neighbor 29.156.0.1 remote-as 29
 neighbor 29.156.0.1 update-source lo
 neighbor 29.157.0.1 remote-as 29
 neighbor 29.157.0.1 update-source lo
 neighbor 29.158.0.1 remote-as 29
 neighbor 29.158.0.1 update-source lo
 neighbor 179.29.30.2 remote-as 30
 neighbor 179.29.30.2 update-source 179.29.30.1
 !
 address-family ipv4 unicast
  network 29.0.0.0/8
  neighbor 179.29.30.2 route-map ALLOW_ALL in
  neighbor 179.29.30.2 route-map ALLOW_ALL out
 exit-address-family
exit
!
router ospf
 ospf router-id 29.153.0.1
 redistribute connected
 network 29.0.1.0/30 area 0.0.0.0
 network 29.0.3.0/30 area 0.0.0.0
 network 29.0.4.0/30 area 0.0.0.0
 network 29.0.5.0/30 area 0.0.0.0
 network 29.0.6.0/30 area 0.0.0.0
exit
!
end
